# Generated by Django 4.2.3 on 2023-07-20 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_post_updated_at_post_uppdated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="uppdated_at",
            new_name="updated_at",
        ),
    ]
