# Generated by Django 4.2.3 on 2023-07-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_rename_uppdated_at_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
