# Generated by Django 4.2.3 on 2023-07-23 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_post_image_webp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_webp",
        ),
    ]
